### ISSUE TITLE
Bug in getSummaryFile due to bug in readr

### ISSUE THREAD

**Issue by alartin** [HajkD/biomartr#2]
Hi,
There is a bug in readr read_tsv and it only parses partial bacteria assembly_summary file. For example, there is over 80,000 rows and only 40,000 + rows loaded due to the quote. But read_tsv lacks of qoute option and it can be fixed by read_delim which you can set quote option.

**Comment by HajkD** [comment]
Hi Xin,

thank you so much for pointing this out to me!
I wasn't aware of this readr package bug.

I will replace read_tsv by read_delim today and come back to you.

Many thanks!

**Comment by HajkD** [comment]
Hi Xin,

I just fixed the problem.

Please find all news here: https://github.com/HajkD/biomartr/blob/master/NEWS.md#bug-fixes

I now fixed all affected functions: `getSummaryFile()`, `getKingdomAssemblySummary()`, `getMetaGenomeSummary()`, `getENSEMBL.Seq()` and `getENSEMBLGENOMES.Seq()`.

I will submit the new version of biomartr to CRAN in one or two weeks. But you can already install via devtools from github.

Again, many thanks for your help. I appreciate it a lot!
