### ISSUE TITLE
Wildcards?

### ISSUE THREAD

**Issue by dbsseven** [HajkD/biomartr#8]
Hi again,
I'm not sure if this is a suggestion for an enhancement, an issue, or if I am misunderstanding something. 

I have a list of bacterial species for which I want to download genomes. Using 'is.genome.available' searches ~8% of my list is apparently available. However, if I do an some automated webscraping (crudely in python), I get ~23% return rate. It appears many species are deposited with the strain name, and therefore return False on 'is.genome.available' when only 'genus species' is given. While not incorrect in the strictest sense, getting these sequenced strains would be useful to me. Is there a way to include wild-cards in the search, or otherwise get back exact but incomplete matches?

As an example: 
Haloferax prahovense

biomartr::is.genome.available("Haloferax prahovense",db="ensemblgenomes",details=TRUE)
Error: Unfortunately organism 'Haloferax prahovense' is not available at ENSEMBLGENOMES. Please check whether or not the organism name is typed correctly.

vs

http://bacteria.ensembl.org/Multi/Search/Results/genome_bacteria?db=core;q=haloferax%20prahovense;species=all;collection=all;site=ensemblunit;
returns: Haloferax prahovense DSM 18310

**Comment by HajkD** [comment]
Hi @dbsseven 

That is an extremely good point! Thank you very much for pointing this out to me as well.

I also noticed already that the scientific naming convention for bacteria in ensemblgenomes is super annoying to parse. Unfortunately, I didn't have the time yet to write a much more generic parser to capture all possible mis-spellings etc. 

Would you like to contribute a parser that solves the problem?

Otherwise, I will try to take care of this aspect as soon as possible, but it could be that I can only work on that in 2 weeks time.   

Many thanks :)

Hajk

**Comment by dbsseven** [comment]
Hi Hajk,
I'm happy to look into this also and do what I can. However, I have no experience with R so it may take me a while to understand the problem and how to address it. But I'll give it a try.

Best,
David

**Comment by HajkD** [comment]
Hi David,

That sounds great! I really appreciate your contribution.

If you come up with with a generic regular expression that catches all the bacterial name conventions, then I am more than happy to implement it in the retrieval functions myself :)

The time-consuming step is to find out how many different examples there are where (e.g. for bacteria or viruses) the scientific naming convention is violated or special characters are inconsistently used and to account for all these cases with a generic regular expression.

I am very much looking forward to collaborating with you on this problem.

Many thanks and best wishes,
Hajk

**Comment by HajkD** [comment]
Hi @dbsseven,

I tried to address your question and implemented a partial string matching approach in `is.genome.available()` (https://github.com/HajkD/biomartr/commit/69c66a2c5c2a4e81c8925b83034c336a9c2edb20).

The initial version of `is.genome.available()` would have allowed you to retrieve the `Haloferax prahovense` information if you directly use the name `Haloferax prahovense DSM 18310`:

> biomartr::is.genome.available("Haloferax prahovense DSM 18310", db = "ensemblgenomes", details = TRUE)

However, now in the new version of `is.genome.available()`, you can only type `Haloferax prahovense` and a partial matching function will automatically find `Haloferax prahovense DSM 18310`.

> biomartr::is.genome.available("Haloferax prahovense", db = "ensemblgenomes", details = TRUE)

Let me know if that helps already :)

Many thanks again for making me aware of this potential enhancement of `biomartr`.

Best wishes,
Hajk
